#!/bin/bash
#
echo -n "Name the month: "
read month
case $month in
 "1") echo "jaanuar";;
 "2") echo "veebruar";;
 "3") echo "marts";;
 "4") echo "aprill";;
 "5") echo "mai";;
 "6") echo "juuni";;
 "7") echo "juuli";;
 "8") echo "august";;
 "9") echo "september";;
 "10") echo "oktoober";;
 "11") echo "november";;
 "12") echo "detsember";;
esac
