#!/bin/bash
#
#reisi korraldamine
#
# inimeste andmed
echo -n "Siseta reisjate arv: "
read reisijad
# kohtade andmed bussis
echo -n "Sisesta kohtade arv bussis: "
read kohad
#
# arvutused
#
# jagamine inimesed busside vahel nii, et koik kohad bussudes oleks taidetud - sellega
# saame teada, nii palju bussi on vaja
bussid=$(($reisijad / $kohad))
# vaatame, palju on need, kes ei saanud koha bussides - need on yle jaanud reisijad,
#ehk jaagid, kui k6ik kohad on taidetud
ylejaanud=$(($reisijad % $kohad))
#
# kui on olemas ylejaanud, tuleb suurendada busside arv 1 v6rra
if test $ylejaanud -gt 0
then
	# bussid muutuja vajab yledefineerimist, selle parast ymbersalvestamiseks
	# ei kasuta $ marki, aga arvutamisel juba kasutame
	bussid=$(($bussid + 1))
fi
# tulemuste valjastamine
#
echo "Kokku on vaja $bussid taisbussi"
#
# skripti lopp
