#!/bin/bash
#
osch=0
echo "1. Unix (Sun Os)"
echo "2. Linux (Red hat)"
echo -n "Select your os choice [1 or 2]? "
red osch

if [ $osch -eq 1 ] ; then
	echo "You pick up Unix (Sun Os)"
else #### nested if i.e. if within if ######
	if [ $osch -eq 2 ] ; then
		echo "You Pick up Linux (Red Hat)"
	else
		echo "What you don´t like Unix/Linux os."
	fi
fi

#
